# -*- coding: utf-8 -*-
"""지구과학 주제탐구.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E05n8pfzey9isw_ticgyZrUjOxAk9mFb
"""

!pip install pandas

import pandas as pd

df = pd.read_csv('sonar.csv', header=None)
print(df.info())

print(df.head())

df= df.iloc[:,:-1]
display(df)

import seaborn as sns
sns.heatmap(df)

import pandas as pd
import matplotlib.pyplot as plt

df.plot(kind='scatter', x=0, y=27)
df.plot(kind='scatter', x=26, y=27)

from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("sonar.csv")
df.head()



from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

X = df['27']
Y = df['0']

plt.plot(X,Yy, 'o')
plt.show()